/*
 * Created on 13 Jul 2017 ( Time 13:22:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.audit.app.Entities.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "attributes_master"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="attributes_master", catalog="chat_data" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="AttributesMasterEntity.countAll", query="SELECT COUNT(x) FROM AttributesMasterEntity x" )
} )
public class AttributesMasterEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="Attribute_Id", nullable=false)
    private Integer    attributeId  ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="Attribute_Name", length=100)
    private String     attributeName ;

    @Column(name="Attribute_Nickname", length=50)
    private String     attributeNickname ;

    @Column(name="Attribute_Type", length=100)
    private String     attributeType ;

    @Column(name="Attribute_ValidValues", length=100)
    private String     attributeValidvalues ;

    @Column(name="status", length=5)
    private String     status       ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", nullable=false)
    private Date       createdDate  ;

	// "reasonid" (column "reasonId") is not defined by itself because used as FK in a link 
	// "wgLoc" (column "wg_loc") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="reasonId", referencedColumnName="id")
    private ReasonsEntity reasons     ;

    @ManyToOne
    @JoinColumn(name="wg_loc", referencedColumnName="id")
    private DeptLocationEntity deptLocation;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public AttributesMasterEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setAttributeId( Integer attributeId ) {
        this.attributeId = attributeId ;
    }
    public Integer getAttributeId() {
        return this.attributeId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : Attribute_Name ( VARCHAR ) 
    public void setAttributeName( String attributeName ) {
        this.attributeName = attributeName;
    }
    public String getAttributeName() {
        return this.attributeName;
    }

    //--- DATABASE MAPPING : Attribute_Nickname ( VARCHAR ) 
    public void setAttributeNickname( String attributeNickname ) {
        this.attributeNickname = attributeNickname;
    }
    public String getAttributeNickname() {
        return this.attributeNickname;
    }

    //--- DATABASE MAPPING : Attribute_Type ( VARCHAR ) 
    public void setAttributeType( String attributeType ) {
        this.attributeType = attributeType;
    }
    public String getAttributeType() {
        return this.attributeType;
    }

    //--- DATABASE MAPPING : Attribute_ValidValues ( VARCHAR ) 
    public void setAttributeValidvalues( String attributeValidvalues ) {
        this.attributeValidvalues = attributeValidvalues;
    }
    public String getAttributeValidvalues() {
        return this.attributeValidvalues;
    }

    //--- DATABASE MAPPING : status ( VARCHAR ) 
    public void setStatus( String status ) {
        this.status = status;
    }
    public String getStatus() {
        return this.status;
    }

    //--- DATABASE MAPPING : created_date ( TIMESTAMP ) 
    public void setCreatedDate( Date createdDate ) {
        this.createdDate = createdDate;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setReasons( ReasonsEntity reasons ) {
        this.reasons = reasons;
    }
    public ReasonsEntity getReasons() {
        return this.reasons;
    }

    public void setDeptLocation( DeptLocationEntity deptLocation ) {
        this.deptLocation = deptLocation;
    }
    public DeptLocationEntity getDeptLocation() {
        return this.deptLocation;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(attributeId);
        sb.append("]:"); 
        sb.append(attributeName);
        sb.append("|");
        sb.append(attributeNickname);
        sb.append("|");
        sb.append(attributeType);
        sb.append("|");
        sb.append(attributeValidvalues);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(createdDate);
        return sb.toString(); 
    } 

}
