/*
 * Created on 13 Jul 2017 ( Time 13:22:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.audit.app.Entities.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "dept_loc_users"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="dept_loc_users", catalog="chat_data" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="DeptLocUsersEntity.countAll", query="SELECT COUNT(x) FROM DeptLocUsersEntity x" )
} )
public class DeptLocUsersEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="sender", length=5)
    private String     sender       ;

    @Column(name="receiver", length=5)
    private String     receiver     ;

    @Column(name="dept_admin", length=5)
    private String     deptAdmin    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", nullable=false)
    private Date       createdDate  ;

    @Column(name="status", length=15)
    private String     status       ;

	// "deptLocId" (column "dept_loc_id") is not defined by itself because used as FK in a link 
	// "userId" (column "user_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="user_id", referencedColumnName="id")
    private UsersEntity users       ;

    @ManyToOne
    @JoinColumn(name="dept_loc_id", referencedColumnName="id")
    private DeptLocationEntity deptLocation;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public DeptLocUsersEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : sender ( VARCHAR ) 
    public void setSender( String sender ) {
        this.sender = sender;
    }
    public String getSender() {
        return this.sender;
    }

    //--- DATABASE MAPPING : receiver ( VARCHAR ) 
    public void setReceiver( String receiver ) {
        this.receiver = receiver;
    }
    public String getReceiver() {
        return this.receiver;
    }

    //--- DATABASE MAPPING : dept_admin ( VARCHAR ) 
    public void setDeptAdmin( String deptAdmin ) {
        this.deptAdmin = deptAdmin;
    }
    public String getDeptAdmin() {
        return this.deptAdmin;
    }

    //--- DATABASE MAPPING : created_date ( TIMESTAMP ) 
    public void setCreatedDate( Date createdDate ) {
        this.createdDate = createdDate;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }

    //--- DATABASE MAPPING : status ( VARCHAR ) 
    public void setStatus( String status ) {
        this.status = status;
    }
    public String getStatus() {
        return this.status;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setUsers( UsersEntity users ) {
        this.users = users;
    }
    public UsersEntity getUsers() {
        return this.users;
    }

    public void setDeptLocation( DeptLocationEntity deptLocation ) {
        this.deptLocation = deptLocation;
    }
    public DeptLocationEntity getDeptLocation() {
        return this.deptLocation;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(sender);
        sb.append("|");
        sb.append(receiver);
        sb.append("|");
        sb.append(deptAdmin);
        sb.append("|");
        sb.append(createdDate);
        sb.append("|");
        sb.append(status);
        return sb.toString(); 
    } 

}
