/*
 * Created on 13 Jul 2017 ( Time 13:22:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.audit.app.Entities.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "dept_loc_hours"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="dept_loc_hours", catalog="chat_data" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="DeptLocHoursEntity.countAll", query="SELECT COUNT(x) FROM DeptLocHoursEntity x" )
} )
public class DeptLocHoursEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="start_time", length=45)
    private String     startTime    ;

    @Column(name="end_time", length=45)
    private String     endTime      ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", nullable=false)
    private Date       createdDate  ;

    @Column(name="days", length=45)
    private String     days         ;

    @Column(name="status", length=15)
    private String     status       ;

    @Column(name="day")
    private Integer    day          ;

    @Column(name="month")
    private Integer    month        ;

	// "deptLocId" (column "dept_loc_Id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="dept_loc_Id", referencedColumnName="id")
    private DeptLocationEntity deptLocation;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public DeptLocHoursEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : start_time ( VARCHAR ) 
    public void setStartTime( String startTime ) {
        this.startTime = startTime;
    }
    public String getStartTime() {
        return this.startTime;
    }

    //--- DATABASE MAPPING : end_time ( VARCHAR ) 
    public void setEndTime( String endTime ) {
        this.endTime = endTime;
    }
    public String getEndTime() {
        return this.endTime;
    }

    //--- DATABASE MAPPING : created_date ( TIMESTAMP ) 
    public void setCreatedDate( Date createdDate ) {
        this.createdDate = createdDate;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }

    //--- DATABASE MAPPING : days ( VARCHAR ) 
    public void setDays( String days ) {
        this.days = days;
    }
    public String getDays() {
        return this.days;
    }

    //--- DATABASE MAPPING : status ( VARCHAR ) 
    public void setStatus( String status ) {
        this.status = status;
    }
    public String getStatus() {
        return this.status;
    }

    //--- DATABASE MAPPING : day ( INT ) 
    public void setDay( Integer day ) {
        this.day = day;
    }
    public Integer getDay() {
        return this.day;
    }

    //--- DATABASE MAPPING : month ( INT ) 
    public void setMonth( Integer month ) {
        this.month = month;
    }
    public Integer getMonth() {
        return this.month;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setDeptLocation( DeptLocationEntity deptLocation ) {
        this.deptLocation = deptLocation;
    }
    public DeptLocationEntity getDeptLocation() {
        return this.deptLocation;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(startTime);
        sb.append("|");
        sb.append(endTime);
        sb.append("|");
        sb.append(createdDate);
        sb.append("|");
        sb.append(days);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(day);
        sb.append("|");
        sb.append(month);
        return sb.toString(); 
    } 

}
