/*
 * Created on 13 Jul 2017 ( Time 13:22:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.audit.app.Entities.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "device_id_list"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="device_id_list", catalog="chat_data" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="DeviceIdListEntity.countAll", query="SELECT COUNT(x) FROM DeviceIdListEntity x" )
} )
public class DeviceIdListEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="device_id", length=145)
    private String     deviceId     ;

    @Column(name="access_key", length=1000)
    private String     accessKey    ;

    @Column(name="count")
    private Integer    count        ;

    @Column(name="status", length=5)
    private String     status       ;

    @Column(name="environment", length=15)
    private String     environment  ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public DeviceIdListEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : device_id ( VARCHAR ) 
    public void setDeviceId( String deviceId ) {
        this.deviceId = deviceId;
    }
    public String getDeviceId() {
        return this.deviceId;
    }

    //--- DATABASE MAPPING : access_key ( VARCHAR ) 
    public void setAccessKey( String accessKey ) {
        this.accessKey = accessKey;
    }
    public String getAccessKey() {
        return this.accessKey;
    }

    //--- DATABASE MAPPING : count ( INT ) 
    public void setCount( Integer count ) {
        this.count = count;
    }
    public Integer getCount() {
        return this.count;
    }

    //--- DATABASE MAPPING : status ( VARCHAR ) 
    public void setStatus( String status ) {
        this.status = status;
    }
    public String getStatus() {
        return this.status;
    }

    //--- DATABASE MAPPING : environment ( VARCHAR ) 
    public void setEnvironment( String environment ) {
        this.environment = environment;
    }
    public String getEnvironment() {
        return this.environment;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(deviceId);
        sb.append("|");
        sb.append(accessKey);
        sb.append("|");
        sb.append(count);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(environment);
        return sb.toString(); 
    } 

}
