/*
 * Created on 13 Jul 2017 ( Time 13:22:23 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.audit.app.Entities.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "locations"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="locations", catalog="chat_data" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="LocationsEntity.countAll", query="SELECT COUNT(x) FROM LocationsEntity x" )
} )
public class LocationsEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="location_name", length=45)
    private String     locationName ;

    @Column(name="location_description", length=245)
    private String     locationDescription ;

    @Column(name="status", length=15)
    private String     status       ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", nullable=false)
    private Date       createdDate  ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="locations", targetEntity=NotificationsEntity.class)
    private List<NotificationsEntity> listOfNotifications;

    @OneToMany(mappedBy="locations", targetEntity=DeptLocationEntity.class)
    private List<DeptLocationEntity> listOfDeptLocation;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public LocationsEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : location_name ( VARCHAR ) 
    public void setLocationName( String locationName ) {
        this.locationName = locationName;
    }
    public String getLocationName() {
        return this.locationName;
    }

    //--- DATABASE MAPPING : location_description ( VARCHAR ) 
    public void setLocationDescription( String locationDescription ) {
        this.locationDescription = locationDescription;
    }
    public String getLocationDescription() {
        return this.locationDescription;
    }

    //--- DATABASE MAPPING : status ( VARCHAR ) 
    public void setStatus( String status ) {
        this.status = status;
    }
    public String getStatus() {
        return this.status;
    }

    //--- DATABASE MAPPING : created_date ( TIMESTAMP ) 
    public void setCreatedDate( Date createdDate ) {
        this.createdDate = createdDate;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfNotifications( List<NotificationsEntity> listOfNotifications ) {
        this.listOfNotifications = listOfNotifications;
    }
    public List<NotificationsEntity> getListOfNotifications() {
        return this.listOfNotifications;
    }

    public void setListOfDeptLocation( List<DeptLocationEntity> listOfDeptLocation ) {
        this.listOfDeptLocation = listOfDeptLocation;
    }
    public List<DeptLocationEntity> getListOfDeptLocation() {
        return this.listOfDeptLocation;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(locationName);
        sb.append("|");
        sb.append(locationDescription);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(createdDate);
        return sb.toString(); 
    } 

}
