/*
 * Created on 13 Jul 2017 ( Time 13:22:23 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.audit.app.Entities.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "reasons"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="reasons", catalog="chat_data" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ReasonsEntity.countAll", query="SELECT COUNT(x) FROM ReasonsEntity x" )
} )
public class ReasonsEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="reason_name", length=45)
    private String     reasonName   ;

    @Column(name="reason_description", length=245)
    private String     reasonDescription ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", nullable=false)
    private Date       createdDate  ;

    @Column(name="status", length=15)
    private String     status       ;

	// "departmentId" (column "department_id") is not defined by itself because used as FK in a link 
	// "reasonGroup" (column "reason_group") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="reason_group", referencedColumnName="ReasonGroup_Id")
    private ReasonGroupEntity reasonGroup2;

    @ManyToOne
    @JoinColumn(name="department_id", referencedColumnName="id")
    private DepartmentsEntity departments ;

    @OneToMany(mappedBy="reasons", targetEntity=AttributesMasterEntity.class)
    private List<AttributesMasterEntity> listOfAttributesMaster;

    @OneToMany(mappedBy="reasons", targetEntity=DeptSkillsMapEntity.class)
    private List<DeptSkillsMapEntity> listOfDeptSkillsMap;

    @OneToMany(mappedBy="reasons", targetEntity=ChatSessionEntity.class)
    private List<ChatSessionEntity> listOfChatSession;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ReasonsEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : reason_name ( VARCHAR ) 
    public void setReasonName( String reasonName ) {
        this.reasonName = reasonName;
    }
    public String getReasonName() {
        return this.reasonName;
    }

    //--- DATABASE MAPPING : reason_description ( VARCHAR ) 
    public void setReasonDescription( String reasonDescription ) {
        this.reasonDescription = reasonDescription;
    }
    public String getReasonDescription() {
        return this.reasonDescription;
    }

    //--- DATABASE MAPPING : created_date ( TIMESTAMP ) 
    public void setCreatedDate( Date createdDate ) {
        this.createdDate = createdDate;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }

    //--- DATABASE MAPPING : status ( VARCHAR ) 
    public void setStatus( String status ) {
        this.status = status;
    }
    public String getStatus() {
        return this.status;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setReasonGroup2( ReasonGroupEntity reasonGroup2 ) {
        this.reasonGroup2 = reasonGroup2;
    }
    public ReasonGroupEntity getReasonGroup2() {
        return this.reasonGroup2;
    }

    public void setDepartments( DepartmentsEntity departments ) {
        this.departments = departments;
    }
    public DepartmentsEntity getDepartments() {
        return this.departments;
    }

    public void setListOfAttributesMaster( List<AttributesMasterEntity> listOfAttributesMaster ) {
        this.listOfAttributesMaster = listOfAttributesMaster;
    }
    public List<AttributesMasterEntity> getListOfAttributesMaster() {
        return this.listOfAttributesMaster;
    }

    public void setListOfDeptSkillsMap( List<DeptSkillsMapEntity> listOfDeptSkillsMap ) {
        this.listOfDeptSkillsMap = listOfDeptSkillsMap;
    }
    public List<DeptSkillsMapEntity> getListOfDeptSkillsMap() {
        return this.listOfDeptSkillsMap;
    }

    public void setListOfChatSession( List<ChatSessionEntity> listOfChatSession ) {
        this.listOfChatSession = listOfChatSession;
    }
    public List<ChatSessionEntity> getListOfChatSession() {
        return this.listOfChatSession;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(reasonName);
        sb.append("|");
        sb.append(reasonDescription);
        sb.append("|");
        sb.append(createdDate);
        sb.append("|");
        sb.append(status);
        return sb.toString(); 
    } 

}
