/*
 * Created on 13 Jul 2017 ( Time 13:22:23 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.audit.app.Entities.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "session_attributes"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="session_attributes", catalog="chat_data" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="SessionAttributesEntity.countAll", query="SELECT COUNT(x) FROM SessionAttributesEntity x" )
} )
public class SessionAttributesEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="attribute_id")
    private Integer    attributeId  ;

    @Column(name="attribute_value", length=45)
    private String     attributeValue ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date")
    private Date       createdDate  ;

    @Column(name="status", length=15)
    private String     status       ;

    @Column(name="session_id")
    private Integer    sessionId    ;

    @Column(name="attribute_name", length=15)
    private String     attributeName ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public SessionAttributesEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : attribute_id ( INT ) 
    public void setAttributeId( Integer attributeId ) {
        this.attributeId = attributeId;
    }
    public Integer getAttributeId() {
        return this.attributeId;
    }

    //--- DATABASE MAPPING : attribute_value ( VARCHAR ) 
    public void setAttributeValue( String attributeValue ) {
        this.attributeValue = attributeValue;
    }
    public String getAttributeValue() {
        return this.attributeValue;
    }

    //--- DATABASE MAPPING : created_date ( DATETIME ) 
    public void setCreatedDate( Date createdDate ) {
        this.createdDate = createdDate;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }

    //--- DATABASE MAPPING : status ( VARCHAR ) 
    public void setStatus( String status ) {
        this.status = status;
    }
    public String getStatus() {
        return this.status;
    }

    //--- DATABASE MAPPING : session_id ( INT ) 
    public void setSessionId( Integer sessionId ) {
        this.sessionId = sessionId;
    }
    public Integer getSessionId() {
        return this.sessionId;
    }

    //--- DATABASE MAPPING : attribute_name ( VARCHAR ) 
    public void setAttributeName( String attributeName ) {
        this.attributeName = attributeName;
    }
    public String getAttributeName() {
        return this.attributeName;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(attributeId);
        sb.append("|");
        sb.append(attributeValue);
        sb.append("|");
        sb.append(createdDate);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(sessionId);
        sb.append("|");
        sb.append(attributeName);
        return sb.toString(); 
    } 

}
