/*
 * Created on 13 Jul 2017 ( Time 13:22:23 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.audit.app.Entities.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "settings"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="settings", catalog="chat_data" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="SettingsEntity.countAll", query="SELECT COUNT(x) FROM SettingsEntity x" )
} )
public class SettingsEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="name", length=45)
    private String     name         ;

    @Column(name="type", length=45)
    private String     type         ;

    @Column(name="value", length=255)
    private String     value        ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date")
    private Date       createdDate  ;

    @Column(name="comments", length=45)
    private String     comments     ;

    @Column(name="short_val", length=15)
    private String     shortVal     ;

    @Column(name="special_val", length=45)
    private String     specialVal   ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public SettingsEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : name ( VARCHAR ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    //--- DATABASE MAPPING : type ( VARCHAR ) 
    public void setType( String type ) {
        this.type = type;
    }
    public String getType() {
        return this.type;
    }

    //--- DATABASE MAPPING : value ( VARCHAR ) 
    public void setValue( String value ) {
        this.value = value;
    }
    public String getValue() {
        return this.value;
    }

    //--- DATABASE MAPPING : created_date ( DATETIME ) 
    public void setCreatedDate( Date createdDate ) {
        this.createdDate = createdDate;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }

    //--- DATABASE MAPPING : comments ( VARCHAR ) 
    public void setComments( String comments ) {
        this.comments = comments;
    }
    public String getComments() {
        return this.comments;
    }

    //--- DATABASE MAPPING : short_val ( VARCHAR ) 
    public void setShortVal( String shortVal ) {
        this.shortVal = shortVal;
    }
    public String getShortVal() {
        return this.shortVal;
    }

    //--- DATABASE MAPPING : special_val ( VARCHAR ) 
    public void setSpecialVal( String specialVal ) {
        this.specialVal = specialVal;
    }
    public String getSpecialVal() {
        return this.specialVal;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(name);
        sb.append("|");
        sb.append(type);
        sb.append("|");
        sb.append(value);
        sb.append("|");
        sb.append(createdDate);
        sb.append("|");
        sb.append(comments);
        sb.append("|");
        sb.append(shortVal);
        sb.append("|");
        sb.append(specialVal);
        return sb.toString(); 
    } 

}
